language: node_js

branches:
  only:
    - master

node_js:
  - "0.10"

services:
  - mongodb  

before_script:
  - npm install -g grunt-cli
  - mkdir -p shippable/testresults
  - mkdir -p shippable/codecoverage
  
after_success:
  - cp -R ./coverage ./shippable/codecoverage
  - cp -R ./reports ./shippable/testresults 
  