language: node_js

branches:
  only:
    - master

node_js:
  - "0.10"

services:
  - mongodb  

before_script:
  - npm install -g grunt-cli
  - npm install -g istanbul
  
after_success:
  - istanbul cover jasmine-node --captureExceptions spec/ && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
  